#ifndef RESPONSECODES_HPP
# define RESPONSECODES_HPP

# define OK 200
# define DELETED 204
# define MULTIPLE_CHOICES 300
# define MOVED_PERMANENTLY 301 // JMA: temporarily added
# define TEMPORARY_REDIRECT 307
# define PERMANENT_REDIRECT 308
# define BAD_REQUEST 400
# define FORBIDDEN 403
# define NOT_FOUND 404
# define METHOD_NOT_ALLOWED 405
# define REQUEST_TIMEOUT 408
# define CONTENT_TOO_LARGE 413
# define INTERNAL_SERVER_ERROR 500
# define NOT_IMPLEMENTED 501

#endif